# Generated by Django 2.2.1 on 2019-08-12 04:46

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WriterInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicname', models.CharField(max_length=64)),
                ('summary', models.TextField()),
                ('details', ckeditor.fields.RichTextField()),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('w', 'Withdrawn')], default='d', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('url', models.CharField(max_length=64)),
                ('seotitle', models.TextField(max_length=100)),
                ('seodescription', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='')),
                ('infomessage', models.TextField(max_length=1000)),
                ('keyword', models.TextField(max_length=100)),
                ('reasearchtime', models.DateTimeField()),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('w', 'Withdrawn')], default='d', max_length=1)),
                ('topicname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogpost.WriterInformation')),
            ],
        ),
        migrations.CreateModel(
            name='EditorInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.BooleanField()),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('w', 'Withdrawn')], default='d', max_length=1)),
                ('topicname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogpost.WriterInformation')),
            ],
        ),
    ]
