# Generated by Django 2.2.1 on 2019-08-17 09:19

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0002_auto_20190812_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchinformation',
            name='topicname',
        ),
        migrations.RemoveField(
            model_name='writerinformation',
            name='topicname',
        ),
        migrations.AddField(
            model_name='seoinformation',
            name='details',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='seoinformation',
            name='infomessage',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='seoinformation',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seoinformation',
            name='publishedtime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='seoinformation',
            name='reasearchtime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='seoinformation',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='seoinformation',
            name='writtentime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='seoinformation',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='seoinformation',
            name='keyword',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='seoinformation',
            name='seodescription',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='seoinformation',
            name='seotitle',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='seoinformation',
            name='title',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='seoinformation',
            name='topicname',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='seoinformation',
            name='url',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.DeleteModel(
            name='EditorInformation',
        ),
        migrations.DeleteModel(
            name='ResearchInformation',
        ),
        migrations.DeleteModel(
            name='WriterInformation',
        ),
    ]
